database:
  connection:
    database: luxe_db_dev
    host: dev-db.example.com
    password: ABCDEERT
    port: 5432
    user: dev_user
    options: ?sslmode=require&channelBinding=require
    sslmode: require